/**
 * Client-side simulation: be the client, and drive the rest from your inbox.
 *
 * Unlike simulate-flow.ts (which drives every step programmatically and asserts
 * on the result), this stops after the two emails a real client would receive
 * first. From there you click through as gbrown would: read the proposal, ask
 * for changes or accept it, pick a payment schedule, and sign.
 *
 * It submits a real intake through the public endpoint, so the acknowledgement
 * and the full recap are generated by the same code a live submission uses,
 * not by anything test-specific.
 *
 * Run: npm run simulate:client
 */
import { createClient } from "@supabase/supabase-js";
import { transporter, SENDERS } from "../src/lib/mail";
import { emailTemplate, emailParagraph, emailInfoCard, emailButton, emailDivider, emailSignoff } from "../src/lib/email-templates";
import { resolveCc } from "../src/lib/cc-recipients";
import { documentTotal, fmtMoney } from "../src/lib/document-html/blocks";

import { DEMO_CLIENT_EMAIL, DEMO_CLIENT_NAME, assertDemoRecipient } from "./demo-target";

const BASE = process.env.SIM_BASE_URL ?? "http://localhost:3000";
const CLIENT_EMAIL = DEMO_CLIENT_EMAIL;
const CLIENT_NAME = DEMO_CLIENT_NAME;

const line = (s = "") => console.log(s);

async function main() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL!;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY!;
  const supabase = createClient(url, key, { auth: { persistSession: false } });

  line("\n\x1b[1m\x1b[36mCLIENT SIMULATION\x1b[0m");
  line(`   You are: ${CLIENT_NAME} <${CLIENT_EMAIL}>`);
  line(`   Base:    ${BASE}\n`);

  // ── 1. Submit the intake, through the real public endpoint ───────────────
  line("\x1b[1m1. Submitting the intake form\x1b[0m");

  const submission = {
    submitter_name: CLIENT_NAME,
    submitter_email: CLIENT_EMAIL,
    submitter_company: "Demo Client Ltd",
    submitter_role: "Director",
    submitter_phone: "+254 700 000 000",
    preferred_contact: "email",
    service_type: "website",
    service_types: ["website"],
    project_title: "Recruitment website rebuild",
    description:
      "Our current site has been down for a few weeks and we have no way for people to apply online. Everything comes through WhatsApp and we lose track of who is serious.",
    problem_statement:
      "We get plenty of enquiries from social media but almost none of them turn into enrolments, and we cannot tell which ones are worth following up.",
    success_criteria:
      "A site that is actually online, that people can apply through, and numbers we can look at each month to see what is working.",
    reference_links: "We like how clean chan-f.or.ke used to look before it went down.",
    industry: "Education",
    business_summary: "We train healthcare and caregiving professionals and place them with employers.",
    target_audience: "School leavers and career changers looking to get into caregiving, plus their parents.",
    online_presence: "Facebook and TikTok are active. The website is currently offline.",
    timeline: "1 to 2 months",
    hard_deadline: "Before the November intake opens",
    budget_range: "KES 100,000 - 200,000",
    budget_confidence: "flexible",
    decision_stage: "ready",
    heard_from: "Referral",
    additional_notes:
      "We have plenty of graduation photos and a few written testimonials we can share. We do not have a logo file, only a picture of the signboard.",
    assets: { logo: false, brand_guidelines: false, copy: true, images: true, domain: true, hosting: false, content_plan: false },
    specifics: {
      website: {
        current_site: "chan-f.or.ke, currently down",
        pages_needed: ["Home", "About", "Courses", "Admissions", "Gallery", "Contact"],
        has_current_system: false,
        needs_online_payments: false,
        content_ready: "Partly",
      },
    },
    contact_consent: true,
    cc_emails: [],
  };

  const intakeRes = await fetch(`${BASE}/api/intake`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(submission),
  });
  const intakeBody = await intakeRes.json().catch(() => ({}));

  if (!intakeRes.ok) {
    line(`   \x1b[31mFAILED\x1b[0m ${JSON.stringify(intakeBody).slice(0, 400)}`);
    process.exit(1);
  }
  line(`   \x1b[32mok\x1b[0m    submitted, ${intakeBody.editsRemaining} revisions allowed`);
  line(`   \x1b[32mok\x1b[0m    two emails sent: the acknowledgement, then the full recap`);
  if (intakeBody.editUrl) line(`         revise at: ${BASE}${intakeBody.editUrl}`);

  // ── 2. Reset and send the proposal ───────────────────────────────────────
  line("\n\x1b[1m2. Sending the proposal\x1b[0m");

  const { data: client } = await supabase
    .from("clients").select("id, name, email").eq("email", CLIENT_EMAIL).is("deleted_at", null).maybeSingle();
  if (!client) throw new Error("Client not found after intake submission.");

  const { data: proposal } = await supabase
    .from("generated_documents")
    .select("*")
    .eq("client_id", client.id)
    .like("reference_code", "DEMO-PROP-%")
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();
  if (!proposal) throw new Error("No demo proposal. Run npm run seed:demo-proposal first.");

  // Start from a clean slate so the whole journey is available to click through.
  await supabase.from("generated_documents").update({
    accepted_at: null, accepted_by_name: null, accepted_by_email: null, accepted_by_role: null,
    accepted_notes: null, chosen_schedule: null, changes_requested_at: null,
    changes_requested_by: null, changes_requested_note: null,
    first_viewed_at: null, view_count: 0, status: "sent", sent_at: new Date().toISOString(),
  }).eq("id", proposal.id);

  const { data: oldAgreements } = await supabase
    .from("generated_documents").select("id").eq("source_document_id", proposal.id).eq("type", "agreement");
  for (const a of oldAgreements ?? []) {
    await supabase.from("projects").delete().eq("source_document_id", a.id);
    await supabase.from("invoices").delete().eq("document_id", a.id);
    await supabase.from("document_signatures").delete().eq("document_id", a.id);
    await supabase.from("generated_documents").delete().eq("id", a.id);
  }

  const proposalUrl = `${BASE}/api/public/documents/${proposal.id}`;
  const total = documentTotal(proposal.data);
  const cc = await resolveCc({ clientId: client.id, scope: "documents", to: CLIENT_EMAIL });

  assertDemoRecipient(CLIENT_EMAIL);
  await transporter.sendMail({
    from: SENDERS.info,
    to: CLIENT_EMAIL,
    cc,
    subject: `Your proposal from Brightex Solutions: ${proposal.title}`,
    html: emailTemplate({
      title: "Your proposal",
      subtitle: proposal.reference_code ?? undefined,
      preheader: "Your website proposal is ready to read",
      heroLabel: "Proposal ready",
      heroTitle: "Here is the plan\nwe put together.",
      body:
        emailParagraph(`Hello ${CLIENT_NAME.split(" ")[0]}, thank you for the call and for filling in the questionnaire so thoroughly. Based on what you told us, here is what we would do, how long it would take, and what it would cost.`) +
        emailInfoCard("📄", "Proposal", `${proposal.title}${proposal.reference_code ? ` (${proposal.reference_code})` : ""}`) +
        (total ? emailInfoCard("💰", "Investment", `KES ${fmtMoney(total)}`) : "") +
        emailInfoCard("🗓️", "Timeline", "6 to 8 weeks, across 3 phases") +
        emailButton("Read the proposal", proposalUrl) +
        emailDivider() +
        emailParagraph("Take your time with it. At the end you can accept it, or tell us what needs changing first and we will set up a call to talk it through. Nothing is committed either way.") +
        emailSignoff(),
    }),
    text:
      `Hello ${CLIENT_NAME.split(" ")[0]},\n\n` +
      `Thank you for the call and for filling in the questionnaire so thoroughly. Here is the proposal.\n\n` +
      `${proposal.title}${proposal.reference_code ? ` (${proposal.reference_code})` : ""}\n` +
      (total ? `Investment: KES ${fmtMoney(total)}\n` : "") +
      `Timeline: 6 to 8 weeks across 3 phases\n\n` +
      `Read it here: ${proposalUrl}\n\n` +
      `At the end you can accept it, or tell us what needs changing first.\n\n` +
      `Best regards,\nThe Brightex Solutions Team`,
  });

  await supabase.from("communications").insert({
    client_id: client.id,
    type: "email",
    subject: `Proposal sent: ${proposal.title}`,
    body: `Proposal ${proposal.reference_code} sent to ${CLIENT_EMAIL}.`,
    direction: "out",
    status: "sent",
    document_id: proposal.id,
    cc_emails: cc,
  });

  line(`   \x1b[32mok\x1b[0m    proposal emailed to ${CLIENT_EMAIL}`);
  line(`   \x1b[32mok\x1b[0m    copied to ${cc.length ? cc.join(", ") : "nobody"}`);

  line("\n\x1b[1mNow check your inbox. Three emails, in order:\x1b[0m");
  line("   1. We received your requirements   (the acknowledgement)");
  line("   2. Your submission to Brightex     (everything you told us, in full)");
  line("   3. Your proposal from Brightex     (the link to read and accept)\n");
  line("\x1b[1mFrom the proposal you can:\x1b[0m");
  line("   · request changes        we get your note and email you back");
  line("   · accept it              choose 60/40 or 40/20/40, then we prepare the agreement");
  line("");
  line(`   Proposal link: ${proposalUrl}`);
  line("");
}

main().catch((err) => { console.error(err); process.exit(1); });
